version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: |
      %(asctime)s - %(name)s - %(filename)s - %(levelname)s
      %(message)s

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  # Temporarily do not use the log file
  # file:
  #   class: logging.handlers.RotatingFileHandler
  #   level: INFO
  #   formatter: standard
  #   filename: 'app.log'
  #   encoding: 'utf8'
  #   maxBytes: 10485760  # 10MB
  #   backupCount: 5

common_logger: &common_logger
  level: DEBUG
  handlers: [console]
  propagate: no

loggers:
  api:
    <<: *common_logger

  mongodb:
    <<: *common_logger

  elasticsearch:
    <<: *common_logger

  openai_api:
    <<: *common_logger

  other_services:
    <<: *common_logger

  utils:
    <<: *common_logger

root:
  level: WARNING
  handlers: [console]